name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Network & Communication
  web_socket_channel: ^2.4.1
  http: ^1.1.0
  
  # State Management
  flutter_riverpod: ^2.4.10
  riverpod: ^2.4.10
  
  # Routing
  go_router: ^12.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true